/**
 * Tracks a link click or button interaction event
 * @param eventLabel The specific action or element that was clicked
 * @param eventCategory The category of the event (default: 'primary')
 * @param eventValue Optional numeric value associated with the event (default: 1)
 */
export function trackLinkClick(
  eventLabel: string,
  eventCategory: string = "primary",
  eventValue: number = 1
): void {
  try {
  if (process.env.NODE_ENV === "production") {
    useTrackEvent(eventLabel, {
      event_category: eventCategory,
      event_label: eventLabel,
      value: eventValue,
    });
    }
  } catch (error) {
    console.error("Error tracking event:", error);
  }
}

/**
 * X Ads event IDs are formatted as `tw-{pixelId}-{eventCode}` (X Ads Manager > Events Manager).
 * The event code is generated by X when the conversion event is created; it is not the
 * event's display name. Codes below belong to pixel `qrrlm`.
 */
const X_PIXEL_EVENT_CODES = {
  sign_up: "repiv",
  login: "repjc",
  credits_claimed: "repjd",
  purchase: "repjg",
  workload_created: "repjp",
} as const;

/**
 * Fires an X (Twitter) Pixel conversion event
 * @param key Logical event key, mapped to its X Ads event code
 * @param parameters Additional event parameters (e.g. value, currency)
 */
export function trackPixelEvent(
  key: keyof typeof X_PIXEL_EVENT_CODES,
  parameters: Record<string, any> = {}
): void {
  try {
    if (process.env.NODE_ENV === "production" && typeof window !== "undefined" && (window as any).twq) {
      const pixelId = useRuntimeConfig().public.x_pixel_id;
      (window as any).twq("event", `tw-${pixelId}-${X_PIXEL_EVENT_CODES[key]}`, parameters);
    }
  } catch (error) {
    console.error("Error tracking pixel event:", error);
  }
}

/**
 * Tracks a general custom event
 * @param eventName The name of the event
 * @param parameters Additional event parameters
 */
export function trackEvent(
  eventName: string,
  parameters: Record<string, any> = {}
): void {
  try {
    if (process.env.NODE_ENV === "production") {
      let contextParams: Record<string, any> = {};

      if (typeof window !== "undefined") {
        try {
          const searchParams = new URLSearchParams(
            window.location.search || ""
          );
          const urlContext = searchParams.get("context");
          let contextValue: string | null = null;

          if (urlContext) {
            contextValue = urlContext;
            try {
              window.sessionStorage.setItem("nosana_context", urlContext);
            } catch {
              // Ignore sessionStorage errors
            }
          } else {
            try {
              contextValue = window.sessionStorage.getItem("nosana_context");
            } catch {
              // Ignore sessionStorage errors
            }
          }

          if (contextValue && !("context" in parameters)) {
            contextParams = { context: contextValue };
          }
        } catch {
          // Ignore URL parsing errors and fall back to original parameters
        }
      }

      useTrackEvent(eventName, {
        ...parameters,
        ...contextParams,
      });
    }
  } catch (error) {
    console.error("Error tracking event:", error);
  }
}
